# https://github.com/nextjs/deploy-github-pages/blob/main/.github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  # Run on pushes to main
  push:
    branches:
      - main
  # Can also be triggered manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OBSIDIAN_AUTH_TOKEN: ${{ secrets.OBSIDIAN_AUTH_TOKEN }}
      CONTENT_VAULT_ID: ${{ secrets.CONTENT_VAULT_ID }}
      CONTENT_VAULT_PASSWORD: ${{ secrets.CONTENT_VAULT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Download content
        run: |
          npx ob sync-setup --path vault --device-name GitHub --vault $CONTENT_VAULT_ID --password $CONTENT_VAULT_PASSWORD
          npx ob sync --path vault
          mv vault/Web/content .
          rm -rf vault
      - name: Setup Pages
        id: setup_pages
        uses: actions/configure-pages@v5
      - name: Build site
        run: npm run build
        env:
          PAGES_BASE_PATH: ${{ steps.setup_pages.outputs.base_path }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4